name: default-pipeline
on:
  push:
    branches:
      - main
  # push:
  #     branches:
  #       - "refs/tags/*"
jobs:
  pre-build-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.24.2"
      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: Check for compilation errors
        run: go build ./cmd/dhee
      - name: Check formatting
        run: gofumpt -w -l . && git diff --exit-code
      - name: Run tests
        run: go test ./...
  build-docker-image:
    runs-on: ubuntu-latest
    needs: [pre-build-checks]
    # if: ${{ startsWith(github.ref, 'refs/tags/') }}
    env:
      TAG_NAME: ${{ github.ref_name }}
      IMAGE_NAME: ghcr.io/mahesh-hegde/dhee
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Docker build
        run: docker build -t "${IMAGE_NAME}:latest" --platform linux/amd64 .
      - name: Push latest image
        run: docker push $IMAGE_NAME:latest
      - name: Tag image
        run: docker tag $IMAGE_NAME:latest $IMAGE_NAME:${TAG_NAME#v}
      - name: Push tagged image
        run: docker push $IMAGE_NAME:${TAG_NAME#v}
